// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ReservationItemStatus.
const (
	Cancelled ReservationItemStatus = "cancelled"
	Expired   ReservationItemStatus = "expired"
	Fulfilled ReservationItemStatus = "fulfilled"
	Pending   ReservationItemStatus = "pending"
)

// Valid indicates whether the value is a known member of the ReservationItemStatus enum.
func (e ReservationItemStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Expired:
		return true
	case Fulfilled:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// AddStockRequest defines model for AddStockRequest.
type AddStockRequest struct {
	// Quantity Quantity to add
	//
	// Example: 100
	Quantity int `json:"quantity"`
}

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error code
	//
	// Example: STOCK_NOT_FOUND
	Error string `json:"error"`

	// Message Error message
	//
	// Example: Stock not found for product
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: inventory-service
	Service string `json:"service"`

	// Status Example: healthy
	Status    string     `json:"status"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// LowStockResponse defines model for LowStockResponse.
type LowStockResponse struct {
	// Count Number of products below threshold
	//
	// Example: 5
	Count    int             `json:"count"`
	Products []StockResponse `json:"products"`

	// Threshold Stock threshold used
	//
	// Example: 10
	Threshold int `json:"threshold"`
}

// ReservationItem defines model for ReservationItem.
type ReservationItem struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Reservation ID
	Id openapi_types.UUID `json:"id"`

	// OrderId Order ID
	OrderId openapi_types.UUID `json:"order_id"`

	// ProductId Product ID
	ProductId openapi_types.UUID `json:"product_id"`

	// Quantity Reserved quantity
	Quantity int `json:"quantity"`

	// Status Reservation status
	Status ReservationItemStatus `json:"status"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// ReservationItemStatus Reservation status
type ReservationItemStatus string

// ReservationsResponse defines model for ReservationsResponse.
type ReservationsResponse struct {
	// Count Number of reservations
	//
	// Example: 3
	Count int `json:"count"`

	// OrderId Order ID
	OrderId      openapi_types.UUID `json:"order_id"`
	Reservations []ReservationItem  `json:"reservations"`
}

// SetStockRequest defines model for SetStockRequest.
type SetStockRequest struct {
	// Quantity New stock quantity
	//
	// Example: 50
	Quantity int `json:"quantity"`
}

// StockResponse defines model for StockResponse.
type StockResponse struct {
	// Available Available stock (not reserved)
	Available int `json:"available"`

	// ProductId Product ID
	ProductId openapi_types.UUID `json:"product_id"`

	// Reserved Reserved stock (held for pending orders)
	Reserved int `json:"reserved"`

	// Total Total stock (available + reserved)
	Total int `json:"total"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// ListLowStockParams defines parameters for ListLowStock.
type ListLowStockParams struct {
	// Threshold Stock threshold (default 10)
	Threshold *int `form:"threshold,omitempty" json:"threshold,omitempty"`
}

// AddStockJSONRequestBody defines body for AddStock for application/json ContentType.
type AddStockJSONRequestBody = AddStockRequest

// SetStockJSONRequestBody defines body for SetStock for application/json ContentType.
type SetStockJSONRequestBody = SetStockRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// HealthCheck Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// GetReservationsByOrder Get reservations for an order
	// (GET /reservations/{orderId})
	GetReservationsByOrder(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)
	// ListLowStock List low stock products
	// (GET /stocks/low)
	ListLowStock(w http.ResponseWriter, r *http.Request, params ListLowStockParams)
	// GetStock Get stock for a product
	// (GET /stocks/{productId})
	GetStock(w http.ResponseWriter, r *http.Request, productId openapi_types.UUID)
	// AddStock Add stock
	// (POST /stocks/{productId}/add)
	AddStock(w http.ResponseWriter, r *http.Request, productId openapi_types.UUID)
	// SetStock Set stock
	// (POST /stocks/{productId}/set)
	SetStock(w http.ResponseWriter, r *http.Request, productId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// HealthCheck Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReservationsByOrder Get reservations for an order
// (GET /reservations/{orderId})
func (_ Unimplemented) GetReservationsByOrder(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListLowStock List low stock products
// (GET /stocks/low)
func (_ Unimplemented) ListLowStock(w http.ResponseWriter, r *http.Request, params ListLowStockParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetStock Get stock for a product
// (GET /stocks/{productId})
func (_ Unimplemented) GetStock(w http.ResponseWriter, r *http.Request, productId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AddStock Add stock
// (POST /stocks/{productId}/add)
func (_ Unimplemented) AddStock(w http.ResponseWriter, r *http.Request, productId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SetStock Set stock
// (POST /stocks/{productId}/set)
func (_ Unimplemented) SetStock(w http.ResponseWriter, r *http.Request, productId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReservationsByOrder operation middleware
func (siw *ServerInterfaceWrapper) GetReservationsByOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReservationsByOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLowStock operation middleware
func (siw *ServerInterfaceWrapper) ListLowStock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLowStockParams

	// ------------- Optional query parameter "threshold" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "threshold", r.URL.Query(), &params.Threshold, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "threshold"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "threshold", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLowStock(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStock operation middleware
func (siw *ServerInterfaceWrapper) GetStock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStock(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddStock operation middleware
func (siw *ServerInterfaceWrapper) AddStock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddStock(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetStock operation middleware
func (siw *ServerInterfaceWrapper) SetStock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetStock(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stocks/{productId}", wrapper.GetStock)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/stocks/{productId}/add", wrapper.AddStock)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/stocks/{productId}/set", wrapper.SetStock)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stocks/low", wrapper.ListLowStock)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reservations/{orderId}", wrapper.GetReservationsByOrder)
	})

	return r
}
