// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthResponseStatus.
const (
	Healthy HealthResponseStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	default:
		return false
	}
}

// AddItemRequest defines model for AddItemRequest.
type AddItemRequest struct {
	// ImageUrl URL of the product image
	//
	// Example: https://example.com/images/mouse.jpg
	ImageUrl *string `json:"image_url,omitempty"`

	// Name Product name
	//
	// Example: Wireless Mouse
	Name string `json:"name"`

	// PriceCents Price per unit in cents
	//
	// Example: 2990
	PriceCents int `json:"price_cents"`

	// ProductId Product identifier
	//
	// Example: prod-456
	ProductId string `json:"product_id"`

	// Quantity Quantity to add
	//
	// Example: 2
	Quantity int `json:"quantity"`
}

// Cart defines model for Cart.
type Cart struct {
	// CreatedAt When the cart was created
	CreatedAt time.Time `json:"created_at"`

	// ItemCount Number of unique items in the cart
	//
	// Example: 3
	ItemCount *int `json:"item_count,omitempty"`

	// Items List of items in the cart
	Items []CartItem `json:"items"`

	// TotalPrice Total price in cents
	//
	// Example: 15990
	TotalPrice int `json:"total_price"`

	// TotalQuantity Total quantity of all items
	//
	// Example: 7
	TotalQuantity *int `json:"total_quantity,omitempty"`

	// UpdatedAt When the cart was last updated
	UpdatedAt time.Time `json:"updated_at"`

	// UserId User who owns this cart
	//
	// Example: user-123
	UserId string `json:"user_id"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	// ImageUrl URL of the product image
	//
	// Example: https://example.com/images/mouse.jpg
	ImageUrl *string `json:"image_url,omitempty"`

	// Name Product name (cached from product service)
	//
	// Example: Wireless Mouse
	Name string `json:"name"`

	// PriceCents Price per unit in cents
	//
	// Example: 2990
	PriceCents int `json:"price_cents"`

	// ProductId Product identifier
	//
	// Example: prod-456
	ProductId string `json:"product_id"`

	// Quantity Quantity of this item
	//
	// Example: 2
	Quantity int `json:"quantity"`

	// Subtotal Subtotal for this item (price_cents * quantity)
	//
	// Example: 5980
	Subtotal int `json:"subtotal"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error code
	//
	// Example: CART_NOT_FOUND
	Error string `json:"error"`

	// Message Human-readable error message
	//
	// Example: Cart not found for user
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: cart-service
	Service string `json:"service"`

	// Status Example: healthy
	Status    HealthResponseStatus `json:"status"`
	Timestamp *time.Time           `json:"timestamp,omitempty"`
}

// HealthResponseStatus Example: healthy
type HealthResponseStatus string

// UpdateQuantityRequest defines model for UpdateQuantityRequest.
type UpdateQuantityRequest struct {
	// Quantity New quantity for the item
	//
	// Example: 3
	Quantity int `json:"quantity"`
}

// ProductIdParam Example: prod-456
type ProductIdParam = string

// UserIdParam Example: user-123
type UserIdParam = string

// AddItemJSONRequestBody defines body for AddItem for application/json ContentType.
type AddItemJSONRequestBody = AddItemRequest

// UpdateItemQuantityJSONRequestBody defines body for UpdateItemQuantity for application/json ContentType.
type UpdateItemQuantityJSONRequestBody = UpdateQuantityRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ClearCart Clear cart
	// (DELETE /carts/{userId})
	ClearCart(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// GetCart Get user's cart
	// (GET /carts/{userId})
	GetCart(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// AddItem Add item to cart
	// (POST /carts/{userId}/items)
	AddItem(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// RemoveItem Remove item from cart
	// (DELETE /carts/{userId}/items/{productId})
	RemoveItem(w http.ResponseWriter, r *http.Request, userId UserIdParam, productId ProductIdParam)
	// UpdateItemQuantity Update item quantity
	// (PUT /carts/{userId}/items/{productId})
	UpdateItemQuantity(w http.ResponseWriter, r *http.Request, userId UserIdParam, productId ProductIdParam)
	// HealthCheck Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ClearCart Clear cart
// (DELETE /carts/{userId})
func (_ Unimplemented) ClearCart(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCart Get user's cart
// (GET /carts/{userId})
func (_ Unimplemented) GetCart(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AddItem Add item to cart
// (POST /carts/{userId}/items)
func (_ Unimplemented) AddItem(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RemoveItem Remove item from cart
// (DELETE /carts/{userId}/items/{productId})
func (_ Unimplemented) RemoveItem(w http.ResponseWriter, r *http.Request, userId UserIdParam, productId ProductIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateItemQuantity Update item quantity
// (PUT /carts/{userId}/items/{productId})
func (_ Unimplemented) UpdateItemQuantity(w http.ResponseWriter, r *http.Request, userId UserIdParam, productId ProductIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HealthCheck Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ClearCart operation middleware
func (siw *ServerInterfaceWrapper) ClearCart(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearCart(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCart operation middleware
func (siw *ServerInterfaceWrapper) GetCart(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCart(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItem operation middleware
func (siw *ServerInterfaceWrapper) AddItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItem(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveItem operation middleware
func (siw *ServerInterfaceWrapper) RemoveItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveItem(w, r, userId, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItemQuantity operation middleware
func (siw *ServerInterfaceWrapper) UpdateItemQuantity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItemQuantity(w, r, userId, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/carts/{userId}", wrapper.ClearCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/carts/{userId}", wrapper.GetCart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/carts/{userId}/items", wrapper.AddItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/carts/{userId}/items/{productId}", wrapper.RemoveItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/carts/{userId}/items/{productId}", wrapper.UpdateItemQuantity)
	})

	return r
}
